try:
    b=float(40+3/0)
exception Exception as e:
    print('This is argument called',e)
